[project]
name = "atividade-pdi"
version = "1.0.0"
dependencies = [
    "numpy>=1.24",
    "pillow>=9.0",
    "matplotlib>=3.5",
    "fpdf>=1.7.2",
    "python-docx>=1.2.0",
]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
